version: '3.4'

services:
  redis-server:
    image: redis
  visit-count:
    image: dhvlptl/visit-count
    build: .
    depends_on:
      - redis-server
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000