version: '3.4'

services:
  redis-server:
    image: redis
  visit-count:
    image: dhvlptl/visit-count
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - redis-server
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
  visit-count-ui:
    image: dhvlptl/visit-count-ui
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - visit-count
    environment:
      NODE_ENV: production
    ports:
      - 80:80